<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="carcompany" nsURI="http://www.example.org/carcompany" nsPrefix="carcompany">
  <eClassifiers xsi:type="ecore:EClass" name="Company" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ford" eSuperTypes="#//Company"/>
  <eClassifiers xsi:type="ecore:EClass" name="BMW" eSuperTypes="#//Company"/>
  <eClassifiers xsi:type="ecore:EClass" name="VAZ" eSuperTypes="#//Company"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mazda" eSuperTypes="#//Company"/>
</ecore:EPackage>
